<?php

namespace Modules\Outlet\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Modules\Outlet\Models\Outlet;
use Modules\Outlet\Models\TypeOutlet;

class OutletSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $restaurantType = TypeOutlet::where('name_type', 'Restaurant')->first();
        $fastFoodType = TypeOutlet::where('name_type', 'Fast Food')->first();
        $beveragesType = TypeOutlet::where('name_type', 'Beverages')->first();
        $foodType = TypeOutlet::where('name_type', 'Food')->first();
        $storeType = TypeOutlet::where('name_type', 'Store')->first();

        if (!$restaurantType) {
            $this->command->warn('No type outlets found. Please run TypeOutletSeeder first.');
            return;
        }

        $outlets = [
            // ── Restaurant ──
            [
                'name' => 'Malis Restaurant',
                'address' => '136 Norodom Blvd, Phnom Penh, Cambodia',
                'phone' => '+855 23 221 022',
                'email' => 'malis@example.com',
                'type_outlet_id' => $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=400&fit=crop',
                'latitude' => 11.5564,
                'longitude' => 104.9282,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '07:00:00',
                'schedule_end_time' => '22:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Romdeng Restaurant',
                'address' => '74 Street 174, Phnom Penh, Cambodia',
                'phone' => '+855 23 219 565',
                'email' => 'romdeng@example.com',
                'type_outlet_id' => $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&h=400&fit=crop',
                'latitude' => 11.5684,
                'longitude' => 104.9210,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '10:00:00',
                'schedule_end_time' => '22:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Topaz Restaurant',
                'address' => '162 Norodom Blvd, Phnom Penh, Cambodia',
                'phone' => '+855 23 221 622',
                'email' => 'topaz@example.com',
                'type_outlet_id' => $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=400&fit=crop',
                'latitude' => 11.5590,
                'longitude' => 104.9295,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '11:00:00',
                'schedule_end_time' => '23:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Siem Reap Khmer Kitchen',
                'address' => 'Pub Street, Siem Reap, Cambodia',
                'phone' => '+855 63 123 456',
                'email' => 'khmerkitchen@example.com',
                'type_outlet_id' => $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=800&h=400&fit=crop',
                'latitude' => 13.3527,
                'longitude' => 103.8560,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '08:00:00',
                'schedule_end_time' => '23:00:00',
                'schedule_status' => 'active',
            ],

            // ── Fast Food ──
            [
                'name' => 'Burger Kingdom',
                'address' => 'AEON Mall Sen Sok, Phnom Penh, Cambodia',
                'phone' => '+855 23 900 111',
                'email' => 'burgerkingdom@example.com',
                'type_outlet_id' => $fastFoodType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&h=400&fit=crop',
                'latitude' => 11.5725,
                'longitude' => 104.8968,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '09:00:00',
                'schedule_end_time' => '22:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Lucky Fried Chicken',
                'address' => '88 Monivong Blvd, Phnom Penh, Cambodia',
                'phone' => '+855 23 900 222',
                'email' => 'luckyfc@example.com',
                'type_outlet_id' => $fastFoodType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=800&h=400&fit=crop',
                'latitude' => 11.5620,
                'longitude' => 104.9180,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '08:00:00',
                'schedule_end_time' => '21:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Pizza Express PP',
                'address' => 'TK Avenue, Phnom Penh, Cambodia',
                'phone' => '+855 23 900 333',
                'email' => 'pizzaexpress@example.com',
                'type_outlet_id' => $fastFoodType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&h=400&fit=crop',
                'latitude' => 11.5740,
                'longitude' => 104.9050,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '10:00:00',
                'schedule_end_time' => '22:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Wok & Roll',
                'address' => 'Street 51, BKK1, Phnom Penh, Cambodia',
                'phone' => '+855 23 900 444',
                'email' => 'wokroll@example.com',
                'type_outlet_id' => $fastFoodType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=400&fit=crop',
                'latitude' => 11.5560,
                'longitude' => 104.9240,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '09:00:00',
                'schedule_end_time' => '21:30:00',
                'schedule_status' => 'active',
            ],

            // ── Beverages ──
            [
                'name' => 'Brown Coffee BKK',
                'address' => 'Street 57, BKK1, Phnom Penh, Cambodia',
                'phone' => '+855 23 800 111',
                'email' => 'brownbkk@example.com',
                'type_outlet_id' => $beveragesType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=400&fit=crop',
                'latitude' => 11.5540,
                'longitude' => 104.9230,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '06:30:00',
                'schedule_end_time' => '21:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Koi Thé Cambodia',
                'address' => 'AEON Mall 1, Phnom Penh, Cambodia',
                'phone' => '+855 23 800 222',
                'email' => 'koithe@example.com',
                'type_outlet_id' => $beveragesType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1558857563-b371033873b8?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&h=400&fit=crop',
                'latitude' => 11.5499,
                'longitude' => 104.9355,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '09:00:00',
                'schedule_end_time' => '21:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Tiger Sugar PP',
                'address' => 'Russian Blvd, Phnom Penh, Cambodia',
                'phone' => '+855 23 800 333',
                'email' => 'tigersugar@example.com',
                'type_outlet_id' => $beveragesType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=800&h=400&fit=crop',
                'latitude' => 11.5650,
                'longitude' => 104.8900,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '09:00:00',
                'schedule_end_time' => '22:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Fresh Juice Corner',
                'address' => 'Riverside, Sisowath Quay, Phnom Penh, Cambodia',
                'phone' => '+855 23 800 444',
                'email' => 'freshjuice@example.com',
                'type_outlet_id' => $beveragesType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800&h=400&fit=crop',
                'latitude' => 11.5735,
                'longitude' => 104.9310,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '07:00:00',
                'schedule_end_time' => '20:00:00',
                'schedule_status' => 'active',
            ],

            // ── Food ──
            [
                'name' => 'Phsar Kandal Street Food',
                'address' => 'Street 130, Phnom Penh, Cambodia',
                'phone' => '+855 23 700 111',
                'email' => 'phasrkandal@example.com',
                'type_outlet_id' => $foodType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&h=400&fit=crop',
                'latitude' => 11.5700,
                'longitude' => 104.9260,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '05:30:00',
                'schedule_end_time' => '20:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Nom Banh Chok House',
                'address' => 'Street 360, Toul Kork, Phnom Penh, Cambodia',
                'phone' => '+855 23 700 222',
                'email' => 'nombanhchok@example.com',
                'type_outlet_id' => $foodType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&h=400&fit=crop',
                'latitude' => 11.5780,
                'longitude' => 104.9100,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '05:00:00',
                'schedule_end_time' => '14:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'BBQ Garden Night Market',
                'address' => 'Night Market, Siem Reap, Cambodia',
                'phone' => '+855 63 700 333',
                'email' => 'bbqgarden@example.com',
                'type_outlet_id' => $foodType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&h=400&fit=crop',
                'latitude' => 13.3600,
                'longitude' => 103.8590,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '16:00:00',
                'schedule_end_time' => '23:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Lok Lak Express',
                'address' => 'Olympic Market Area, Phnom Penh, Cambodia',
                'phone' => '+855 23 700 444',
                'email' => 'loklak@example.com',
                'type_outlet_id' => $foodType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=400&fit=crop',
                'latitude' => 11.5580,
                'longitude' => 104.9120,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '06:00:00',
                'schedule_end_time' => '21:00:00',
                'schedule_status' => 'active',
            ],

            // ── Store ──
            [
                'name' => 'Lucky Supermarket TK',
                'address' => 'Toul Kork, Phnom Penh, Cambodia',
                'phone' => '+855 23 600 111',
                'email' => 'luckytk@example.com',
                'type_outlet_id' => $storeType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=400&fit=crop',
                'latitude' => 11.5800,
                'longitude' => 104.9050,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '07:00:00',
                'schedule_end_time' => '22:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Mini Mart 24h Riverside',
                'address' => 'Sisowath Quay, Phnom Penh, Cambodia',
                'phone' => '+855 23 600 222',
                'email' => 'minimart@example.com',
                'type_outlet_id' => $storeType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&h=400&fit=crop',
                'latitude' => 11.5730,
                'longitude' => 104.9320,
                'status' => 'active',
                'schedule_mode' => 'always',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Khmer Goods Market',
                'address' => 'Central Market Area, Phnom Penh, Cambodia',
                'phone' => '+855 23 600 333',
                'email' => 'khmergoods@example.com',
                'type_outlet_id' => $storeType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1528698827591-e19cef51a699?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1604754742629-3e5728249d73?w=800&h=400&fit=crop',
                'latitude' => 11.5700,
                'longitude' => 104.9210,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '06:00:00',
                'schedule_end_time' => '19:00:00',
                'schedule_status' => 'active',
            ],
            [
                'name' => 'Siem Reap Souvenir Shop',
                'address' => 'Old Market Area, Siem Reap, Cambodia',
                'phone' => '+855 63 600 444',
                'email' => 'souvenir@example.com',
                'type_outlet_id' => $storeType?->id ?? $restaurantType->id,
                'logo' => 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=200&h=200&fit=crop',
                'image_url' => 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&h=400&fit=crop',
                'latitude' => 13.3520,
                'longitude' => 103.8550,
                'status' => 'active',
                'schedule_mode' => 'daily',
                'schedule_start_time' => '08:00:00',
                'schedule_end_time' => '21:00:00',
                'schedule_status' => 'active',
            ],
        ];

        foreach ($outlets as $outlet) {
            Outlet::updateOrCreate(
                ['name' => $outlet['name']],
                array_merge($outlet, ['uuid' => Str::uuid()])
            );
        }

        $this->command->info('Outlets seeded successfully. Total: ' . Outlet::count());
    }
}
